image: node

stages:
  - deploy-seller-stg
  - deploy-admin-stg
  - deploy-home-stg
#  - deploy-seller-prod
#  - deploy-admin-prod
#  - deploy-home-prod

cache:
  paths:
    - node_modules/

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan 172.105.122.9 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git config --global user.email "huytd92@gmail.com"
  - git config --global user.name "Duc Huy Ta"

deploy-seller-stg:
  stage: deploy-seller-stg
  environment:
    name: staging
  script:
    - yarn install
    - yarn run build-stg:seller
    - scp -r build/* root@172.105.122.9:/var/www/html/seller.onepage.zclouds.vn/
  only:
    - main

deploy-admin-stg:
  stage: deploy-admin-stg
  environment:
    name: staging
  script:
    - yarn install
    - yarn run build-stg:admin
    - scp -r build/* root@172.105.122.9:/var/www/html/admin.onepage.zclouds.vn/
  only:
    - main

deploy-home-stg:
  stage: deploy-home-stg
  environment:
    name: staging
  script:
    - yarn install
    - yarn run build-stg
    - scp -r build/* root@172.105.122.9:/var/www/html/onepage.zclouds.vn/
  only:
    - main

#deploy-seller-prod:
#  stage: deploy-seller-prod
#  environment:
#    name: production
#  script:
#    - yarn install
#    - yarn run build:seller
#    - scp -P 26266 -r build/* root@139.144.119.195:/var/www/html/seller.onepage.zclouds.vn/
#  only:
#    - master
#
#deploy-admin-prod:
#  stage: deploy-admin-prod
#  environment:
#    name: production
#  script:
#    - yarn install
#    - yarn run build:admin
#    - scp -P 26266 -r build/* root@139.144.119.195:/var/www/html/admin.onepage.zclouds.vn/
#  only:
#    - master
#
#deploy-home-prod:
#  stage: deploy-home-prod
#  environment:
#    name: production
#  script:
#    - yarn install
#    - yarn run build
#    - scp -P 26266 -r build/* root@139.144.119.195:/var/www/html/onepage.zclouds.vn/
#  only:
#    - master

